### ISSUE TITLE
Requires a specific version (1.5.1) of AgilityPack

### ISSUE THREAD

**Issue by jonathanbp** [atifaziz/Hazz#4]
Would it be possible to make the requirement AgilityPack >=1.5.1 instead of AgilityPack = 1.5.1?

**Comment by atifaziz** [comment]
It would have been, but unfortunately, HtmlAgilityPack does not follow semantic versioning (see zzzprojects/html-agility-pack#74) so there's no guarantee that some version 1.x >= 1.5.1 is backward compatible. Just because it passes the tests in this project doesn't mean that it won't break some other application that uses both.

**Comment by jonathanbp** [comment]
Alright.
